
# Configurações para a Netlify

[build]
  # Diretório onde os arquivos estáticos e as funções serverless são gerados
  publish = ".next"
  command = "next build"

[build.environment]
  # Desativa o auto-update do Genkit durante o build
  GENKIT_TELEMETRY_DISABLED = "true"

[[plugins]]
  # Plugin oficial da Netlify para Next.js
  package = "@netlify/plugin-nextjs"

    